/**
 * Set de íconos de la plataforma: Bootstrap Icons (react-bootstrap-icons).
 *
 * Se exportan con los nombres semánticos que usa la interfaz para que los
 * componentes importen desde un solo lugar (`import { Activity } from
 * '../lib/icons'`) y el set pueda cambiarse sin tocar cada archivo.
 * Todos aceptan `size`, `className` y `color`.
 * @module icons
 */
export {
  Activity,
  ExclamationCircle as AlertCircle,
  ExclamationTriangle as AlertTriangle,
  ArrowRight,
  Award,
  BarChartLine as BarChart3,
  JournalBookmark as BookMarked,
  Book as BookOpen,
  Box,
  Briefcase,
  Building,
  Calculator,
  Calendar3 as Calendar,
  Check2 as Check,
  CheckCircle,
  CheckCircle as CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CardChecklist as ClipboardList,
  Clock,
  CodeSlash as Code2,
  Cpu,
  Database,
  Download,
  BoxArrowUpRight as ExternalLink,
  Eye,
  FileEarmarkMusic as FileAudio,
  FileEarmarkArrowDown as FileDown,
  FileEarmarkSpreadsheet as FileSpreadsheet,
  FileEarmarkText as FileText,
  Fire as Flame,
  Flask as FlaskConical,
  GlobeAmericas as Globe,
  Mortarboard as GraduationCap,
  Grid3x3 as Grid3X3,
  HouseDoor as Home,
  Image,
  InfoCircle as Info,
  Layers,
  JournalText as Library,
  ListUl as List,
  ArrowRepeat as Loader,
  Lock,
  BoxArrowInRight as LogIn,
  BoxArrowRight as LogOut,
  Envelope as Mail,
  GeoAlt as MapPin,
  ChatSquareText as MessageSquare,
  Triangle as Mountain,
  PauseFill as Pause,
  Pencil,
  PlayFill as Play,
  PlusLg as Plus,
  Broadcast as Radio,
  ArrowRepeat as RefreshCw,
  ArrowCounterclockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  Save,
  Bank as Scale,
  Search,
  Gear as Settings,
  ShieldLock as Shield,
  ShieldCheck,
  SkipStartFill as SkipBack,
  Bullseye as Target,
  Trash3 as Trash2,
  GraphUpArrow as TrendingUp,
  Upload,
  Person as User,
  PersonCheck as UserCheck,
  PersonPlus as UserPlus,
  PersonX as UserX,
  People as Users,
  Soundwave as Waves,
  XLg as X,
  XCircle,
  LightningCharge as Zap,
} from 'react-bootstrap-icons';
